// Generated by CoffeeScript 1.6.3
/*
    Serialize Anything
    (c) 2013 Moreno Cunha
*/


(function() {
  $.prototype.values = function(data) {
    var inps;
    inps = $(this).find(":input").get();
    if (typeof data !== "object") {
      data = {};
      $.each(inps, function() {
        if (this.name && (this.checked || /select|textarea/i.test(this.nodeName) || /text|hidden|password/i.test(this.type))) {
          return data[this.name] = $(this).val();
        }
      });
      return data;
    } else {
      $.each(inps, function() {
        if (this.name && data[this.name]) {
          if (this.type === "checkbox" || this.type === "radio") {
            return $(this).prop("checked", data[this.name] === $(this).val());
          } else {
            return $(this).val(data[this.name]);
          }
        } else if (this.type === "checkbox") {
          return $(this).prop("checked", false);
        }
      });
      return $(this);
    }
  };

}).call(this);
